Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-06, with the labels that each got.

#1318 Default controller manager limits
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1341 Disable configure of cloud route when allocate-node-cidrs is enabled
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1322 Raid0 support
  core/nodepool/config/templates/cloud-config-worker
  core/nodepool/config/templates/stack-template.json
  core/root/config/templates/cluster.yaml
  model/ec2_instance.go
  model/node_pool_config.go
  model/raid0_mount.go
  model/volume_mount.go
  model/volume_mount_test.go
Labels: cncf-cla: yes, size/L

#1338 Update dashboard RBAC to match 1.8.3 requirements
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1339 Instructions for updating the AMI
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/XS

#1323 Make sure that canal and flannel land on all tainted nodes
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/M

#1330 Consistent logging with options to silence, verbosify and color messages
  README.md
  cfnstack/provisioner.go
  cmd/calculator.go
  cmd/destroy.go
  cmd/flag_util.go
  cmd/init.go
  cmd/render.go
  cmd/root.go
  cmd/show.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  cmd/version.go
  core/controlplane/cluster/cluster.go
  core/controlplane/config/config.go
  core/controlplane/config/credential.go
  core/controlplane/config/encrypted_assets.go
  core/etcd/cluster/cluster.go
  core/network/cluster/cluster.go
  core/nodepool/config/config.go
  core/root/cluster.go
  core/root/credentials.go
  logger/color.go
  logger/logger.go
  model/gpu.go
  model/node_pool_config.go
  model/root_volume.go
Labels: cncf-cla: yes, size/L

#1345 Add support for CoreDNS as DNS provider
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/L

#1346 Automatically enable EBS optimization
  core/nodepool/config/templates/stack-template.json
  filereader/texttemplate/texttemplate.go
Labels: cncf-cla: yes, size/S

#1326 added label to kube-system namespace
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/M

#1356 Promote compute reservation options [Small]
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/config.go
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/M

#1354 Consolidate kiam configuration
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1357 Bring etcd's up in parallel on new cluster / Fail-fast to update 0.10.x clusters with newer kube-aws
  .gitignore
  cfnstack/cfnstack.go
  cfnstack/cfnstack_test.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/etcd/cluster/cluster.go
  core/etcd/config/templates/stack-template.json
  core/root/cluster.go
  core/root/config/config.go
  model/etcd.go
  test/helper/cfn.go
  test/integration/maincluster_test.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/L

#1358 Display cluster details when logging into CoreOS
  core/controlplane/cluster/cluster.go
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/etcd/cluster/cluster.go
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/cluster/cluster.go
  core/nodepool/config/config.go
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
  model/bash_prompt.go
  model/motd_banner.go
  model/shell_colour.go
  model/shellcolour_enumer.go
Labels: cncf-cla: yes, size/XL

#1360 Fix duplicate controller role permissions for CloudWatch logging
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/S

#1362 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#1363 Bump go to 1.10.x for travis builds
  .travis.yml
  make/test
Labels: cncf-cla: yes, size/XS

#1361 Implement 'apply' command and deprecate 'up' and 'update'
  cmd/apply.go
  cmd/up.go
  cmd/update.go
  core/root/cluster.go
Labels: cncf-cla: yes, size/L

#1366 Break dependency on etcd from the nodepools
  core/controlplane/config/templates/stack-template.json
  core/nodepool/config/templates/stack-template.json
Labels: cncf-cla: yes, size/S

#1367 Remove node dependency on ETCD Stack when Networking.SelfHosting is Enabled.
  core/nodepool/config/templates/stack-template.json
Labels: cncf-cla: yes, size/S

#1368 Add branch to build version when not a tagged release
  build
Labels: cncf-cla: yes, size/XS

#1365 Fix for rpc-statd.service needed to mount NFS file shares
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/templates/cloud-config-worker
Labels: cncf-cla: yes, size/S

#1374 Correct semantic version checks
  core/controlplane/config/templates/cloud-config-controller
  filereader/texttemplate/texttemplate.go
Labels: cncf-cla: yes, size/S

#1378 Add LICENSE for ebs-automatic-nvme-mapping
  core/nodepool/config/templates/cloud-config-worker
  licenses/LICENSE.ebs-automatic-nvme-mapping
  licenses/README.md
Labels: cncf-cla: yes, size/M
