Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-12, with the labels that each got.

#1505 Minor fixes in documentation
  README.md
  docs/tutorials/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1512 CA self-genereted cert: add the cn flag
  cmd/render.go
  credential/generator.go
  pkg/model/credentials_test.go
  pki/ca.go
Labels: cncf-cla: yes, lgtm, size/S

#1504 A couple of fixes for nodepool resources and cloudwatch logging
  builtin/files/stack-templates/network.json.tmpl
  builtin/files/stack-templates/root.json.tmpl
  pkg/api/worker_node_pool.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1493 v0.11.x - Smooth migration from v0.10.x nodes
  cfnresource/naming.go
  cfnresource/naming_test.go
  cfnstack/cfnstack.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/stack-template.json
  core/etcd/config/templates/cloud-config-etcd
  core/etcd/config/templates/stack-template.json
  core/network/config/templates/stack-template.json
  core/nodepool/config/config.go
  core/root/cluster.go
  make/test
  model/cidr_range.go
  test/integration/aws_test.go
Labels: cncf-cla: yes, size/L

#1515 bug: Nodepool stack needs to use the nodepool logical name
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, size/XS

#1516 Fix for using StrictName to define a specific Controller Role Name
  pkg/api/controller.go
Labels: cncf-cla: yes, size/XS

#1519 Do not leak unqualified dns requests to upstream dns servers
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS
