Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-03, with the labels that each got.

#1164 Apply Kiam TLS Secrets to kube-system
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1154 Update ROADMAP.md
  ROADMAP.md
Labels: cncf-cla: yes, size/S

#1167 Change bash to sh in autosave
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1172 added autoscaling:DescribeAutoScalingGroups to stack-template
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1179 Correct insignificant error message typo
  plugin/clusterextension/extras.go
Labels: cncf-cla: yes, size/XS

#1171 Fix validation failure on gp2 volume type for node pools
  core/nodepool/cluster/cluster.go
  core/nodepool/cluster/cluster_test.go
Labels: cncf-cla: yes, size/M

#1181 Enable DescribeLaunchConfigurations
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1184 Add IAM roles for resources auto saver
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/M

#1177 Integrate s3-uri flag into cluster.yml
  README.md
  cmd/calculator.go
  cmd/init.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  core/controlplane/cluster/cluster.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cluster.yaml
  core/nodepool/cluster/cluster_test.go
  core/nodepool/config/config_test.go
  core/root/cluster.go
  core/root/options.go
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-3-launch.md
  docs/getting-started/step-4-update.md
  docs/getting-started/step-5-add-node-pool.md
  docs/tutorials/quick-start.md
  test/integration/aws_test.go
  test/integration/maincluster_test.go
  test/integration/nodepool_test.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/L

#1189 closes #1186 - commit generated templates so project can be imported
  .gitignore
  build
  core/controlplane/config/config.go
  core/controlplane/config/files.go
  core/controlplane/config/templates.go
  core/nodepool/config/config.go
  core/nodepool/config/templates.go
  core/root/config/config.go
  core/root/config/templates.go
  docs/guides/developer-guide.md
Labels: cncf-cla: yes, size/XXL

#1198 Doc: notice about service token invalidation after credentials update.
  docs/getting-started/step-4-update.md
Labels: cncf-cla: yes, size/XS
