Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-05, with the labels that each got.

#1263 removed unused s3 flags from commands
  cmd/calculator.go
  cmd/destroy.go
  cmd/init.go
  cmd/render.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  cmd/version.go
Labels: size/M

#1241 Disable coreOS auto-updates
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cloud-config-etcd
  core/controlplane/config/templates/cloud-config-worker
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/M

#1281 Fix etcd breakage due to strange systemd behavior
  core/controlplane/config/templates/cloud-config-etcd
Labels: cncf-cla: yes, size/XS

#1266 Allow configure Controller Manager compute resources
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/M

#1274 Allow cfn-signal.service to cleanly start under certain circumstances
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1276 Disable alpha batch APIs by default
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1277 kiam support improvements
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cluster.yaml
  core/nodepool/config/config.go
  core/nodepool/config/config_test.go
  core/nodepool/config/deployment.go
  core/nodepool/config/templates/stack-template.json
  docs/getting-started/step-6-configure-add-ons.md
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1289 Normalize audit log attribute names in cluster.yaml + add support for missing attributes
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1290 Fix failing etcd volume attach when upgrading etcd instances
  core/controlplane/config/templates/cloud-config-etcd
Labels: cncf-cla: yes, size/S

#1292 Enable TLS for communication between control plane components and the local apiserver
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/controlplane/config/templates/cloud-config-controller
  docs/getting-started/step-2-render.md
  test/helper/helper.go
Labels: cncf-cla: yes, size/L

#1293 Add in ExpandPersistentVolumes as part of feature-gates on controller
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1260 Add some limited certificate credential validation
  Gopkg.lock
  README.md
  core/controlplane/cluster/cluster.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/templates/cloud-config-etcd
  gzipcompressor/gzipcompressor.go
  test/helper/helper.go
  tlsutil/pem.go
  tlsutil/x509.go
  vendor/golang.org/x/sys/unix/linux/mkall.go
  vendor/golang.org/x/sys/unix/linux/types.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
Labels: cncf-cla: yes, size/XXL

#1286 Use API server lease reconciler for k8s 1.9+
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/M

#1296 Add support for AWS profile containing source_profile, role_arn, mfa_serial
  awsconn/awsconn.go
  core/controlplane/cluster/cluster.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/etcd/cluster/cluster.go
  core/network/cluster/cluster.go
  core/nodepool/cluster/cluster.go
  core/nodepool/cluster/cluster_test.go
  core/nodepool/cluster/factory.go
  core/nodepool/config/config.go
  core/root/cluster.go
  core/root/describer.go
  core/root/destroyer.go
Labels: cncf-cla: yes, size/L

#900 feat: Encrypting Secret Data at Rest
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
  e2e/run
Labels: cncf-cla: yes, size/L

#1284 Cluster autoscaler docs/tests
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cluster.yaml
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/M

#1299 tlsutil cleanup plus added tests
  cmd/show.go
  core/controlplane/cluster/cluster.go
  core/controlplane/config/encrypted_assets.go
  core/root/credentials.go
  core/root/stack.go
  tlscerts/cert.go
  tlscerts/cert_test.go
  tlsutil/cert.go
  tlsutil/pem.go
  tlsutil/pem_test.go
  tlsutil/x509.go
Labels: cncf-cla: yes, size/XL

#1305 append comma when necessary to the EtcdNodes range
  core/etcd/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1306 Use EtcdStackName for eni provider
  model/derived/etcd_node.go
Labels: cncf-cla: yes, size/XS

#1310 Move templates into their related packages
  build
  cmd/init.go
  core/controlplane/config/config.go
  core/controlplane/config/user_data_config_test.go
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/cluster/cluster_test.go
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/config.go
  core/root/config/templates/cluster.yaml
  core/root/stack.go
  test/integration/maincluster_test.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M

#1308 Handle cluster CIDR changes
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/network/config/templates/stack-template.json
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
  filereader/texttemplate/texttemplate.go
  filereader/texttemplate/texttemplate_test.go
Labels: cncf-cla: yes, size/XL

#1309 Enable Network-Self-Hosting by default
  core/controlplane/config/config.go
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1319 Added the ability to disable the dashboard
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  docs/advanced-topics/kubernetes-dashboard.md
Labels: cncf-cla: yes, size/S

#1320 1316/kiam kube2iam with kube net selfhosting
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1333 Tweak CloudFormation stack descriptions
  core/controlplane/config/templates/stack-template.json
  core/etcd/config/templates/stack-template.json
  core/nodepool/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1334 Fix flannel traffic among controllers
  core/network/config/templates/stack-template.json
Labels: cncf-cla: yes, size/S

#1343 Tag etcd volumes with names
  core/etcd/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1314 Feature/volume mounts for controllers and etcds
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/stack-template.json
  core/etcd/config/templates/cloud-config-etcd
  core/etcd/config/templates/stack-template.json
  core/root/config/templates/cluster.yaml
  model/controller.go
  model/etcd.go
Labels: cncf-cla: yes, size/L

#1335 Fix install-kube-system
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/M
