Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-11, with the labels that each got.

#1477 Adding davidmccormick as a maintainer of kube-aws
  OWNERS
Labels: cncf-cla: yes, size/XS

#1480 Check stack existence via DescribeStacks
  cfnstack/cfnstack.go
  cfnstack/cfnstack_test.go
  test/helper/cfn.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1484 feat: add CF stackNameOverride in cluster.yaml
  core/controlplane/cluster/cluster.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/etcd/cluster/cluster.go
  core/network/cluster/cluster.go
  core/root/config/templates/cluster.yaml
  model/cloudformation.go
  model/stack_name_overrides.go
Labels: cncf-cla: yes, size/L

#1482 Bug/fix cf stack paging v0.12.x
  cfnstack/cfnstack.go
  cfnstack/cfnstack_test.go
  test/helper/cfn.go
Labels: cncf-cla: yes, lgtm, size/M

#1486 v0.11.x: feat: add CF stackNameOverride in cluster.yaml
  core/controlplane/cluster/cluster.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/etcd/cluster/cluster.go
  core/network/cluster/cluster.go
  core/root/config/templates/cluster.yaml
  model/cloudformation.go
  model/stack_name_overrides.go
Labels: cncf-cla: yes, size/L

#1487 v0.12.x: feat: add CF stackNameOverride in cluster.yaml
  core/controlplane/cluster/cluster.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/etcd/cluster/cluster.go
  core/network/cluster/cluster.go
  core/root/config/templates/cluster.yaml
  model/cloudformation.go
  model/stack_name_overrides.go
Labels: cncf-cla: yes, size/L

#1489 Fix some typos
  docs/getting-started/step-2-render.md
Labels: cncf-cla: yes, size/XS

#1495 Fix typos: additioanl->additional, creaes->creates
  awsconn/awsconn.go
Labels: cncf-cla: yes, size/XS

#1499 Change StackExists behaviour
  cfnstack/cfnstack.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1497 IAM Role name length checks need to account for StrictName usage...
  cfnresource/naming.go
  cfnresource/naming_test.go
  pkg/api/cluster.go
  pkg/model/node_pool_config.go
Labels: approved, cncf-cla: yes, lgtm, size/M
