Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-09, with the labels that each got.

#1433 Feature/add custom kiam role
  core/controlplane/config/templates/stack-template.json
  core/root/config/templates/cluster.yaml
  model/iamconfig.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1446 Fix mfdir setting to prevent controller install failure w/ KIAM disabled
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1447 Explicitly set default dnsmasq min-port [Tiny]
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1448 fix: Attach kube-aws controller policy to pre-existing IAM role
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1451 0.12 release: remove legacy networking (less is more)
  Gopkg.lock
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/network/config/templates/stack-template.json
  core/nodepool/config/deployment.go
  core/nodepool/config/templates/cloud-config-worker
  core/nodepool/config/templates/stack-template.json
  core/root/cluster.go
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/XXL

#1452 fix: `encryptionAtRest: true` should not break controller nodes
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1453 fix: `encryptionAtRest: true` should not break controller nodes
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1456 Bump go to 1.11
  .travis.yml
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/encrypted_assets.go
  model/api_endpoints.go
  test/integration/aws_test.go
  tlsutil/x509.go
Labels: cncf-cla: yes, size/M

#1462 fix: `KubernetesDashboard.Enabled: false` should not break controllers
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1459 Bump Kubernetes version to v1.11.3
  contrib/bump-version
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
  e2e/kubernetes/Dockerfile
  e2e/kubernetes/Makefile
Labels: cncf-cla: yes, size/L
