Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-04, with the labels that each got.

#1202 Dedicated Service account / Cluster Role for Tiller Deploy
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/M

#1201 Make CoreOS AMI ID mandatory in cluster YAML
  cmd/init.go
  core/controlplane/config/templates/cluster.yaml
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/S

#1197 do not use metric server when metricsServers addon is disabled
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1205 core: add OwnerReferencesADM
  core/controlplane/config/config.go
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1216 Fix documentation of s3-uri
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/tutorials/quick-start.md
Labels: cncf-cla: yes, size/XS

#1195 Add networking-daemonsets feature
  .gitignore
  core/controlplane/config/config.go
  core/controlplane/config/files.go
  core/controlplane/config/templates.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cloud-config-worker
  core/controlplane/config/templates/cluster.yaml
  core/controlplane/config/templates/stack-template.json
  core/controlplane/config/user_data_config_test.go
  core/nodepool/config/templates.go
  core/root/config/templates.go
  model/userdata.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XXL

#1229 Fix issue with tiller having to restrictive permissions
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1227 Enable user provided service-account-signing-keys
  core/controlplane/config/credential.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1222 Add GPU support for kubernetes 1.9+ using device plugins
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/config.go
  core/nodepool/config/worker.go
  model/gpu.go
  model/node_pool_config.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1234 handle kubectl apply failures by trying delete+create
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1235 Bug/flannel cni binary install
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cloud-config-worker
Labels: cncf-cla: yes, size/S

#1236 Bump Kubernetes to v1.9.3
  contrib/bump-version
  core/controlplane/config/config.go
  core/controlplane/config/templates/cluster.yaml
  e2e/kubernetes/Dockerfile
  e2e/kubernetes/Makefile
Labels: cncf-cla: yes, size/S

#1244 Inherit controlplane Kubenetes-Newtworking config in node pools.
  core/nodepool/config/deployment.go
Labels: cncf-cla: yes, size/XS

#1239 KIAMImage should affect server as well as client.
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1243 Admission Controller for PersistentVolumeClaimResize
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/S

#1249 [Canal] Support tainted worker
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1250 Fix typo of Getting Started.
  docs/getting-started/step-2-render.md
Labels: cncf-cla: yes, size/XS

#1251 Bump Calico/Typha Versions now Typha Issue resolved.
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1259 update kubernetes-dashboard to 1.8.3
  core/controlplane/config/config.go
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/XS
