Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-07, with the labels that each got.

#1376 Bump kubernetes version to 1.10.4
  contrib/bump-version
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
  e2e/kubernetes/Dockerfile
  e2e/kubernetes/Makefile
Labels: cncf-cla: yes, size/S

#1377 Remove kube-system namespace out of kiam if statement
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1383 getting started: fix typo in bucket creation
  docs/getting-started/step-2-render.md
Labels: cncf-cla: yes, size/XS

#1388 Fix colour causing extra newlines
  logger/logger.go
Labels: cncf-cla: yes, size/S

#1389 Added in KIAM session timeout modifier
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XS

#1384 Add apiserver aggregator with certs when metrics server is enabled
  core/controlplane/config/config.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
  core/controlplane/config/templates/cloud-config-controller
  model/addons.go
  test/helper/helper.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1385 Better identification of nodes
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/templates/cloud-config-worker
Labels: cncf-cla: yes, size/S

#1394 Bump Kubernetes to v1.10.5
  contrib/bump-version
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/root/config/templates/cluster.yaml
  e2e/kubernetes/Dockerfile
  e2e/kubernetes/Makefile
Labels: cncf-cla: yes, size/S

#1397 Self hosted calico v3.1.3
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/templates/cloud-config-worker
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/L

#1390 0.11.x Extend CustomFiles to be able to render go templates
  core/controlplane/config/templates/cloud-config-controller
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/config/templates/cloud-config-worker
  model/custom_file.go
  model/custom_file_test.go
Labels: cncf-cla: yes, size/L

#1398 0.10.x Extend CustomFiles to be able to render go templates
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cloud-config-etcd
  core/controlplane/config/templates/cloud-config-worker
  model/custom_file.go
  model/custom_file_test.go
Labels: cncf-cla: yes, size/L

#1400 0.10.x Add kubernetes manifests from customfiles
  core/controlplane/config/templates/cloud-config-controller
  core/controlplane/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1402 0.10.x Remove dependency on alpine:latest
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1399 0.11.x Add kubernetes manifests from customfiles
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1404 Differentiate the node drainer containers
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1409 Add kube-aws:version to stacktags
  cfnstack/provisioner.go
  core/controlplane/cluster/cluster.go
  core/nodepool/cluster/cluster.go
  core/root/cluster.go
Labels: cncf-cla: yes, size/S

#1410 Update reserved storage flag name
  core/controlplane/config/config_test.go
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1412 Resolve CFN dependency issue when updating to v0.10.x
  core/controlplane/config/templates/stack-template.json
Labels: cncf-cla: yes, size/XS

#1413 Improve customFile templating
  core/controlplane/config/templates/cloud-config-controller
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/config/templates/cloud-config-worker
  model/custom_file.go
Labels: cncf-cla: yes, size/XS

#1420 Remove invalid aws tag symbols from branch names
  build
Labels: cncf-cla: yes, size/XS

#1421 cluster.yaml: removed whitespace in waitSignal configuration
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/XS

#1418 Fix dep ensure empty package issue
  core/network/config/config.go
Labels: cncf-cla: yes, size/XS
