Repository kubernetes-incubator/kube-aws, pull requests merged in 2018-10, with the labels that each got.

#1466 Bump calico/typha/flannel, fix cause of calico/typha restarts
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/M

#1471 renamed the --admission-control flag to --enable-admission-plugins in cloud-config-controller template
  core/controlplane/config/templates/cloud-config-controller
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XS

#1470 Allow plugins to add kube-controller-manager command line flags.
  core/controlplane/cluster/cluster.go
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  plugin/clusterextension/extras.go
  plugin/pluginmodel/config.go
Labels: cncf-cla: yes, size/M

#1467 Add a Pod Disruption Budget on kube-dns
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1475 0.12.x: Allow user control over controller.iam.role.name
  core/controlplane/config/templates/stack-template.json
  core/root/config/templates/cluster.yaml
  model/iamconfig.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1476 hack: a bit more automated release note generation
  Makefile
  hack/relnote
  hack/version
Labels: cncf-cla: yes, size/S
