Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-11, with the labels that each got.

#1769 master: CoreDNS prometheus metric annotations exposed at pod level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1770 v0.13.x: CoreDNS prometheus metric annotations exposed at pod level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1771 v0.14.x: CoreDNS prometheus metric annotations exposed at pod level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1765 Missing end
  builtin/files/plugins/dashboard/manifests/deployment.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#1774 Add missing calico networkset crd and rbac permission
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1767 Kube2iam resources adjustment
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1781 fix broken links
  contrib/dex/README.md
  docs/advanced-topics/use-an-existing-vpc.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-5-add-node-pool.md
  e2e/README.md
Labels: cncf-cla: yes, lgtm, size/S

#1775 V0.13.x kube2iam resource increase
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1776 v0.14.x Increase kube2iam resource limits
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1780 Add flag to cmds to use AWS profile
  awsconn/awsconn.go
  cmd/apply.go
  cmd/calculator.go
  cmd/destroy.go
  cmd/diff.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  core/root/cluster.go
  core/root/describer.go
  core/root/destroyer.go
  core/root/options.go
  docs/cli-reference/README.md
Labels: cncf-cla: yes, lgtm, size/M

#1782 Use nodePoolRollingStrategy of 'AvailabilityZone' by default.
  builtin/files/cluster.yaml.tmpl
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  docs/advanced-topics/kubernetes-dashboard.md
  pkg/api/cluster.go
  pkg/api/worker_node_pool.go
  pkg/model/compiler.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1783 Adding in the metricsBindAddress to kube-proxy configmap to allow for…
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1784 Adding in the metricsBindAddress to kube-proxy configmap to allow for…
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1785 Adding in the metricsBindAddress to kube-proxy configmap to allow for…
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1788 Add flag to cmds to use AWS profile
  awsconn/awsconn.go
  cmd/apply.go
  cmd/calculator.go
  cmd/destroy.go
  cmd/diff.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  core/root/cluster.go
  core/root/describer.go
  core/root/destroyer.go
  core/root/options.go
  docs/cli-reference/README.md
Labels: cncf-cla: yes, lgtm, size/M

#1790 Add flag to cmds to use AWS profile
  awsconn/awsconn.go
  cmd/apply.go
  cmd/calculator.go
  cmd/destroy.go
  cmd/diff.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  core/root/cluster.go
  core/root/describer.go
  core/root/destroyer.go
  core/root/options.go
  docs/cli-reference/README.md
Labels: cncf-cla: yes, lgtm, size/M

#1791 Add flag to cmds to use AWS profile
  awsconn/awsconn.go
  cmd/apply.go
  cmd/calculator.go
  cmd/destroy.go
  cmd/diff.go
  cmd/status.go
  cmd/up.go
  cmd/update.go
  cmd/validate.go
  core/root/cluster.go
  core/root/describer.go
  core/root/destroyer.go
  core/root/options.go
  docs/cli-reference/README.md
Labels: cncf-cla: yes, size/M
