Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-12, with the labels that each got.

#1792 update to kubernetes to v1.14.9
  build
Labels: cncf-cla: yes, size/XS

#1793 kubernetes v1.15.6
  build
Labels: cncf-cla: yes, size/XS

#1797 Adding in the metricsBindAddress to kube-proxy configmap to allow for…
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1799 Add autoscaling:DescribeAutoScalingGroups policy for node drainer.
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, size/XS

#1801 Update v0.15.x branch for v0.15.0 release
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/stack-templates/root.json.tmpl
  core/root/cluster.go
  core/root/template_params.go
  pkg/api/existing_etcd.go
  pkg/model/context.go
  pkg/model/stack_new.go
  pkg/model/types.go
Labels: cncf-cla: yes, size/M

#1805 fix typo
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1803 Add autoscaling:DescribeAutoScalingGroups policy for node drainer.
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, lgtm, size/XS

#1802 Add autoscaling:DescribeAutoScalingGroups policy for node drainer.
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, lgtm, size/XS

#1806 [0.12.x Only] Fix ExtraCoreDNSConfig typo in stack template
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS
