Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-08, with the labels that each got.

#1690 Change kiam-server 443 port name
  builtin/files/userdata/cloud-config-controller
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1694 Change kiam-server 443 port name
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1693 Change kiam server port name v0.13.x
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1689 Fix cloud-config-controller
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/L

#1697 v0.13.x: Cherry-pick coredns anti-affinity fix
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1696 V0.14.x: Cherry pick coredns anti-affinity fix
  builtin/files/userdata/cloud-config-controller
Labels: approved, cncf-cla: yes, lgtm, size/M

#1692 v0.12.x: Change kiam-server 443 port name
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, do-not-merge/hold, size/XS

#1691 v0.11.x: Change kiam-server 443 port name
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, do-not-merge/hold, size/XS

#1695 Allow extra Coredns configuration
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1700 Remove duplicated kiam agent flags
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1682 v0.13.x plugin: upgrade helper - more fixes and features
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-post.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-pre.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1683 v0.14.x plugin: upgrade helper - more fixes and features
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-post.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-pre.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1681 plugin: upgrade helper - more fixes and features
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-post.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper-pre.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1668 Fix VPCRef
  builtin/files/stack-templates/network.json.tmpl
  pkg/model/config.go
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/M

#1701 Fix VPCRef (#1668)
  builtin/files/stack-templates/network.json.tmpl
  pkg/model/config.go
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/M

#1702 Fix VPCRef (#1668)
  builtin/files/stack-templates/network.json.tmpl
  pkg/model/config.go
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/M

#1707 kubernetes v1.13.9
  build
Labels: cncf-cla: yes, size/XS

#1708 kubernetes v1.14.5
  build
Labels: cncf-cla: yes, size/XS

#1709 Update launch from up to apply
  docs/tutorials/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS

#1713 v0.13.x: bump kubernetes to v1.13.10
  build
Labels: cncf-cla: yes, size/XS

#1714 master: Kubernetes v1.15.3
  build
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, size/L

#1712 v0.14.x: bump kubernetes to v1.14.6
  build
Labels: cncf-cla: yes, size/XS
