Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-05, with the labels that each got.

#1585 Enable detailed monitoring
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, size/XS

#1586 Custom APIServer SANs
  builtin/files/cluster.yaml.tmpl
  credential/generator.go
  pkg/api/cluster.go
  pkg/model/credentials.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1583 Etcd Subnets not honoured on stack render.
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/S

#1576 Cluster-autoscaler plugin
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/pdb.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/service.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
Labels: cncf-cla: yes, size/L

#1591 Update 0.14 branch
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/pdb.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/service.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
Labels: cncf-cla: yes, size/L

#1596 NAT Gateway tagging #1063
  builtin/files/stack-templates/network.json.tmpl
Labels: cncf-cla: yes, lgtm, size/S

#1598 Issue when kube-aws manages/creates subnets
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  filereader/texttemplate/texttemplate.go
  pkg/api/subnet.go
  pkg/api/subnets.go
  pkg/model/stack.go
  pkg/model/stack_new.go
  pkg/model/types.go
Labels: cncf-cla: yes, size/L

#1599 Allow setting Kiam version <3.0
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1600 V0.13.0 rc.2 prep1
  builtin/files/cluster.yaml.tmpl
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/network.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  filereader/texttemplate/texttemplate.go
  pkg/api/cluster.go
  pkg/api/subnet.go
  pkg/api/subnets.go
  pkg/model/stack.go
  pkg/model/stack_new.go
  pkg/model/types.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1605 Etcd Upgrade
  build
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  builtin/files/etcdadm/test
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  core/root/cluster.go
  pkg/api/cluster.go
  pkg/api/etcd.go
  pkg/api/etcd_cluster.go
  pkg/api/etcd_test.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1608 v0.13.0-rc.2
  build
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  builtin/files/etcdadm/test
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  core/root/cluster.go
  pkg/api/cluster.go
  pkg/api/etcd.go
  pkg/api/etcd_cluster.go
  pkg/api/etcd_test.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1609 v0.14.0-rc.2
  build
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  builtin/files/etcdadm/test
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/network.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  core/root/cluster.go
  filereader/texttemplate/texttemplate.go
  pkg/api/cluster.go
  pkg/api/etcd.go
  pkg/api/etcd_cluster.go
  pkg/api/etcd_test.go
  pkg/api/subnet.go
  pkg/api/subnets.go
  pkg/model/stack.go
  pkg/model/stack_new.go
  pkg/model/types.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/L

#1610 master <- V0.14.x
  build
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1611 Tag instances with their etcd or kubernetes version
  builtin/files/stack-templates/etcd.json.tmpl
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/XS

#1612 Tag instances with their etcd or kubernetes version
  builtin/files/stack-templates/etcd.json.tmpl
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/XS

#1613 Tag instances with their etcd or kubernetes version
  builtin/files/stack-templates/etcd.json.tmpl
  pkg/model/stack_new.go
Labels: cncf-cla: yes, size/XS
