Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-07, with the labels that each got.

#1661 v0.13.x: Plugin enhancement - allow embedding templates within templates
  filereader/texttemplate/texttemplate.go
  plugin/plugincontents/template.go
Labels: cncf-cla: yes, size/XS

#1662 master: Plugin enhancement - allow embedding templates within templates
  filereader/texttemplate/texttemplate.go
  plugin/plugincontents/template.go
Labels: cncf-cla: yes, lgtm, size/XS

#1663 v0.14.x: Plugin enhancement - allow embedding templates within templates
  filereader/texttemplate/texttemplate.go
  plugin/plugincontents/template.go
Labels: cncf-cla: yes, size/XS

#1607 Reserve resources for calico typha
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/networking.go
Labels: cncf-cla: yes, lgtm, size/M

#1664 v0.13.x-Reserve resources for calico typha (#1607)
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/networking.go
Labels: cncf-cla: yes, size/M

#1665 v0.14.x-Reserve resources for calico typha (#1607)
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/networking.go
Labels: cncf-cla: yes, size/M

#1667 Etcd cannot depend on resources in another stack
  builtin/files/stack-templates/etcd.json.tmpl
Labels: cncf-cla: yes, size/XS

#1669 Cannot depend on resources in another stack
  builtin/files/stack-templates/etcd.json.tmpl
Labels: cncf-cla: yes, size/XS

#1670 Cannot depend on resources in another stack
  builtin/files/stack-templates/etcd.json.tmpl
Labels: cncf-cla: yes, size/XS

#1671 Allow an AntiAffinty tolerant to help ensure even spread of DNS pods
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/L

#1672 [v0.13.x] - Allow an AntiAffinty tolerant to help ensure even spread of DNS pods
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1673 [v0.14.x] - Allow an AntiAffinty tolerant to help ensure even spread of DNS pods
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1677 Correct IAM Role Namechecking in v0.12.x branch
  cfnresource/naming.go
  cfnresource/naming_test.go
  core/controlplane/config/config.go
  core/nodepool/config/config.go
Labels: cncf-cla: yes, lgtm, size/M

#1674 v0.13.x: fixes for rendering plugin systemd units
  pkg/api/plugin.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/plugincontents/loader.go
  plugin/plugincontents/template.go
  provisioner/remote_file.go
  provisioner/remote_file_loader.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/XL

#1675 master: Fixes for rendering plugin systemd units
  pkg/api/plugin.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/plugincontents/loader.go
  plugin/plugincontents/template.go
  provisioner/remote_file.go
  provisioner/remote_file_loader.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/XL

#1676 v0.14.x: fixes for rendering plugin systemd units
  pkg/api/plugin.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/plugincontents/loader.go
  plugin/plugincontents/template.go
  provisioner/remote_file.go
  provisioner/remote_file_loader.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/XL

#1678 v0.13.x: Plugin: upgrade-helper
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1679 master: plugin: upgrade-helper
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1680 v0.14.x: plugin: upgrade-helper
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
  builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
  builtin/files/plugins/upgrade-helper/plugin.yaml
Labels: cncf-cla: yes, size/L

#1685 v0.14.x: daemonset roll out settings
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1686 daemonset roll out settings
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S
