Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-10, with the labels that each got.

#1742 Update prompt and banner earlier in boot process
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1743 Update prompt and banner earlier in boot process
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1744 Update prompt and banner earlier in boot process
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1748 Networking Version Updates
  builtin/files/cluster.yaml.tmpl
  pkg/api/cluster.go
Labels: cncf-cla: yes, lgtm, size/S

#1749 [0.13.x] Networking Version Updates
  builtin/files/cluster.yaml.tmpl
  pkg/api/cluster.go
Labels: cncf-cla: yes, lgtm, size/S

#1750 [0.14.x] Networking Version Updates
  builtin/files/cluster.yaml.tmpl
  pkg/api/cluster.go
Labels: cncf-cla: yes, lgtm, size/S

#1747 [v0.14.x] Allow resource configuration for APIServer
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/kubernetes.go
Labels: cncf-cla: yes, lgtm, size/M

#1745 [v0.13.x] Allow resource configuration for APIServer
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/kubernetes.go
Labels: cncf-cla: yes, size/M

#1751 [v0.13.x]Allow extra Coredns configuration
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  core/root/cluster.go
  pkg/api/cluster.go
  pkg/api/node_volume_mount_test.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1752 [v0.14.x] Allow extra Coredns configuration
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  core/root/cluster.go
  pkg/api/cluster.go
  pkg/api/node_volume_mount_test.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1753 [Master] Allow extra Coredns configuration
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  core/root/cluster.go
  pkg/api/cluster.go
  pkg/api/node_volume_mount_test.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1754 Migrate the kubernetes dashboard to a plugin and plugin templating improvements.
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/dashboard/manifests/autoscaler.yaml
  builtin/files/plugins/dashboard/manifests/deployment.yaml
  builtin/files/plugins/dashboard/manifests/metrics-scraper.yaml
  builtin/files/plugins/dashboard/manifests/rbac.yaml
  builtin/files/plugins/dashboard/manifests/secrets.yaml
  builtin/files/plugins/dashboard/plugin.yaml
  builtin/files/userdata/cloud-config-controller
  core/root/cluster.go
  pkg/api/plugin_config.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/plugincontents/render_values.go
  plugin/plugincontents/template.go
  tmpl/text_to_cfn_expr.go
Labels: cncf-cla: yes, size/XXL

#1755 v0.14.x: Remove the control-plane stacks dependence on cross stack references
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/root.json.tmpl
  core/root/template_params.go
  pkg/model/etcd_node.go
Labels: cncf-cla: yes, size/M

#1758 v0.13.x: Allow server certs to also be used for client authentication
  pki/x509.go
Labels: cncf-cla: yes, size/XS

#1760 kubernetes-1.15.5
  build
Labels: cncf-cla: yes, size/XS

#1761 kubernetes v1.14.8
  build
Labels: cncf-cla: yes, size/XS

#1762 V0.13.x kubernetes v1.13.12
  build
Labels: cncf-cla: yes, size/XS
