Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-02, with the labels that each got.

#1548 feat: Option to provide existing private keys.
  cmd/render.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/encrypted_assets_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1551 Fixing adding cf resources to etcd and networking stack v.0.11.x
  core/etcd/config/templates/stack-template.json
  core/network/cluster/cluster.go
  plugin/clusterextension/extras.go
  plugin/pluginmodel/config.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M

#1552 Fixing adding cf resources to etcd and networking stack v.0.12.x
  core/etcd/config/templates/stack-template.json
  core/network/cluster/cluster.go
  plugin/clusterextension/extras.go
  plugin/pluginmodel/config.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M

#1549 feat: Allow users to provide existing private keys
  cmd/render.go
  credential/generator.go
  pkg/model/credentials_test.go
Labels: cncf-cla: yes, size/L

#1555 Revert etcd upgrade
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  builtin/files/etcdadm/etcdadm
  builtin/files/stack-templates/etcd.json.tmpl
  pkg/api/etcd.go
  pkg/api/etcd_test.go
  pkg/api/plugin.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M

#1531 feat: support for AWS mixed instances
  builtin/files/cluster.yaml.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  pkg/api/asg.go
  pkg/api/asg_test.go
  pkg/api/mixed_instances.go
  pkg/api/worker_node_pool.go
Labels: cncf-cla: yes, size/L

#1554 Make cluster-autoscaler resource request/limit configurable
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  model/addons.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1556 Make cluster-autoscaler resource request/limit configurable
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  model/addons.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1557 Make cluster-autoscaler resource request/limit configurable
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/addons.go
Labels: cncf-cla: yes, size/M
