Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-09, with the labels that each got.

#1720 CoreDNS prometheus metric annotations exposed at deployment level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1719 [v0.13.x] CoreDNS prometheus metric annotations exposed at deployment level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1718 [v0.14.x] CoreDNS prometheus metric annotations exposed at deployment level
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1726 move Kiam to a plugin
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/kiam/manifests/agent-daemonset.yaml
  builtin/files/plugins/kiam/manifests/agent-tls-secret.yaml
  builtin/files/plugins/kiam/manifests/server-cluster-role-binding.yaml
  builtin/files/plugins/kiam/manifests/server-cluster-role.yaml
  builtin/files/plugins/kiam/manifests/server-daemonset.yaml
  builtin/files/plugins/kiam/manifests/server-tls-secret.yaml
  builtin/files/plugins/kiam/manifests/service-account.yaml
  builtin/files/plugins/kiam/manifests/service.yaml
  builtin/files/plugins/kiam/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/userdata/cloud-config-controller
  cmd/render.go
  credential/encrypted_assets.go
  credential/encrypted_assets_test.go
  credential/generator.go
  credential/pki.go
  docs/getting-started/step-6-configure-add-ons.md
  pkg/api/cluster.go
  pkg/api/keypair_spec.go
  pkg/api/types.go
  pkg/model/cluster_test.go
  pkg/model/credentials.go
  pkg/model/credentials_test.go
  pkg/model/stack_test.go
  pki/keypair.go
  pki/pki.go
  pki/x509.go
  plugin/clusterextension/extras.go
  test/helper/helper.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, lgtm, size/XXL

#1727 Allow CoreDNS resources to be configured
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1728 [v0.13.x] Allow CoreDNS resources to be configured
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1729 [v0.14.x] Allow CoreDNS resources to be configured
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1730 Move kube2iam to a plugin
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/kube2iam/manifests/daemonset.yaml
  builtin/files/plugins/kube2iam/manifests/rbac.yaml
  builtin/files/plugins/kube2iam/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  docs/getting-started/step-6-configure-add-ons.md
  pkg/api/cluster.go
  pkg/api/types.go
  proposals/plugins.md
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1731 Referencing the drainTimeout value in the NodeDrainer daemonset
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1732 [v0.13.x] Referencing the drainTimeout value in the NodeDrainer daemonset
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1733 [v0.14.x] Referencing the drainTimeout value in the NodeDrainer daemonset
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1735 kube2iam resources improvement
  builtin/files/plugins/kube2iam/manifests/daemonset.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#1736 Bump kubernetes to v0.13.11
  build
Labels: cncf-cla: yes, size/XS

#1738 bump kubernetes to v0.15.4
  build
Labels: cncf-cla: yes, size/XS

#1737 bump kubernetes to v0.14.7
  build
Labels: cncf-cla: yes, lgtm, size/XS

#1739 Take region from the cluster config.
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS

#1740 Take region from the cluster config.
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS

#1741 Take region from the cluster config.
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS
