Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-01, with the labels that each got.

#1522 Fix for kubelet startup on nodes when using TLS bootstrapping
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, size/M

#1521 Move IAMRoleWorker definition from network stack to node pool stack
  builtin/files/stack-templates/network.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/L

#1523 Fixes typo initizlie -> initialize
  core/root/cluster.go
Labels: cncf-cla: yes, size/XS

#1526 Fix to escape % character in systemd config for raid0Mounts
  builtin/files/userdata/cloud-config-worker
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1528 v0.11.x: Add DnsMasq (node local resolver) command-line arguments/options
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1527 Master: Add DnsMasq (node local resolver) command-line arguments/options
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/types.go
Labels: cncf-cla: yes, size/S

#1529 v0.12.x: Add DnsMasq (node local resolver) command-line arguments/options
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
Labels: cncf-cla: yes, size/S

#1524 fix: Partial upgrades with stack name overrides
  core/root/cluster.go
  core/root/operation_targets.go
Labels: cncf-cla: yes, size/M

#1540 Fixing indentation error
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1539 Make dashboard replicas configurable
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  docs/advanced-topics/kubernetes-dashboard.md
  pkg/api/cluster.go
Labels: cncf-cla: yes, size/XS

#1536 Master: Bump default Kubernetes Dashboard version and add AllowSkipLogin option
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  docs/advanced-topics/kubernetes-dashboard.md
  pkg/api/cluster.go
Labels: cncf-cla: yes, size/S

#1538 v0.11.x: Bump default Kubernetes Dashboard version and add AllowSkipLogin option
  core/controlplane/config/config.go
  core/controlplane/config/encrypted_assets.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  docs/advanced-topics/kubernetes-dashboard.md
  model/api_endpoints.go
  tlsutil/x509.go
Labels: cncf-cla: yes, size/M

#1537 v0.12.x: Bump default Kubernetes Dashboard version and add AllowSkipLogin option
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  docs/advanced-topics/kubernetes-dashboard.md
Labels: cncf-cla: yes, size/S

#1535 Backport fix for StackExists behaviour into 0.12.x branch
  cfnstack/cfnstack.go
Labels: cncf-cla: yes, size/S

#1530 fix: Partial upgrades with stack name overrides
  core/root/cluster.go
  core/root/operation_targets.go
Labels: cncf-cla: yes, size/M

#1542 V0.11.x configurable dashboard replicas
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  docs/advanced-topics/kubernetes-dashboard.md
Labels: cncf-cla: yes, lgtm, size/XS

#1543 V0.12.x configurable dashboard replicas
  core/controlplane/config/config.go
  core/controlplane/config/templates/cloud-config-controller
  core/root/config/templates/cluster.yaml
  docs/advanced-topics/kubernetes-dashboard.md
Labels: cncf-cla: yes, size/XS

#1545 Porting "Adding the ability to add feature gates to controller components" to 0.11.X
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/config.go
  test/integration/maincluster_test.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M

#1544 Porting "Adding the ability to add feature gates to controller components" to 0.12.X
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/controlplane/config/templates/cloud-config-controller
  core/nodepool/config/config.go
  test/integration/maincluster_test.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, size/M
