Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-06, with the labels that each got.

#1615 Migrate to plugin based autoscaler and plugin system fixes
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/rbac.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  core/root/config/config.go
  credential/store.go
  docs/getting-started/README.md
  docs/getting-started/step-2-render.md
  pkg/api/addons.go
  pkg/api/autoscaling.go
  pkg/api/cluster.go
  pkg/api/controller.go
  pkg/api/plugin_config.go
  pkg/api/types.go
  pkg/api/worker_node_pool.go
  pkg/model/cluster_test.go
  pkg/model/node_pool_compile.go
  pkg/model/node_pool_config.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/pluginutil/merge_values.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XL

#1619 v0.14.x autoscaler work
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/rbac.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  core/root/config/config.go
  credential/store.go
  docs/getting-started/README.md
  docs/getting-started/step-2-render.md
  pkg/api/addons.go
  pkg/api/autoscaling.go
  pkg/api/cluster.go
  pkg/api/controller.go
  pkg/api/plugin_config.go
  pkg/api/types.go
  pkg/api/worker_node_pool.go
  pkg/model/cluster_test.go
  pkg/model/node_pool_compile.go
  pkg/model/node_pool_config.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/pluginutil/merge_values.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XL

#1618 V0.13.x autoscaler work
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/rbac.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/servicemonitor.yaml
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  core/root/config/config.go
  credential/store.go
  docs/getting-started/README.md
  docs/getting-started/step-2-render.md
  pkg/api/addons.go
  pkg/api/autoscaling.go
  pkg/api/cluster.go
  pkg/api/controller.go
  pkg/api/plugin_config.go
  pkg/api/types.go
  pkg/api/worker_node_pool.go
  pkg/model/cluster_test.go
  pkg/model/node_pool_compile.go
  pkg/model/node_pool_config.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  plugin/pluginutil/merge_values.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XL

#1622 bump kubernetes version to 1.13.7
  build
  builtin/files/userdata/cloud-config-etcd
Labels: cncf-cla: yes, size/XS

#1623 bump kubernetes to v1.14.3
  build
  builtin/files/userdata/cloud-config-etcd
Labels: cncf-cla: yes, size/XS

#1624 fix version string
  builtin/files/userdata/cloud-config-etcd
Labels: cncf-cla: yes, size/XS

#1625 [v0.13.x] Configurable CoreDNS TTL
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1627 Configurable CoreDNS TTL
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1626 [v0.14.x] Configurable CoreDNS TTL
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1630 Make the EventRateLimit alpha admission controller experimental and e…
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  test/integration/maincluster_test.go
Labels: approved, cncf-cla: yes, size/M

#1629 Merge in EventRateLimit to Experimental feature
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1628 Make the EventRateLimit alpha admission controller experimental
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/M

#1632 Update OWNERS.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1633 [0.13.x] Update OWNERS.
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#1634 [0.14.x] Update OWNERS.
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#1631 adding in priority value in podSpec for controller, scheduler and apiserver
  builtin/files/userdata/cloud-config-controller
Labels: approved, cncf-cla: yes, lgtm, size/M

#1649 [v0.14.x] Fix trailing slash in Taint templating.
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1651 [v0.13.x] Fix trailing slash in Taint templating.
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1652 Fix trailing slash in Taint templating.
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1635 [v0.14.x] - Expose CoreDNS to Prometheus
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1637 Expose CoreDNS to Prometheus
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1636 [v0.13.x] - Expose CoreDNS to Prometheus
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1639 v0.11.x: A migration helper to disable core controller services when needed
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1640 v0.12.x: A migration helper to disable core controller services when needed
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1641 master: A migration helper to disable core controller services when needed
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1642 v0.13.x: A migration helper to disable core controller services when needed
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1643 v0.14.x: A migration helper to disable core controller services when needed
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1656 Fix formatting with cluster-autoscaler
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS

#1655 [v0.13.x] Fix formatting with cluster-autoscaler
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS

#1654 [v0.14.x] Fix formatting with cluster-autoscaler
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
Labels: cncf-cla: yes, size/XS

#1646 Etcd version
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/etcdadm
Labels: cncf-cla: yes, size/S

#1657 0.13.x Etcd version (#1646)
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/etcdadm
Labels: approved, cncf-cla: yes, lgtm, size/S

#1658 0.14.x Etcd version (#1646)
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/etcdadm
Labels: approved, cncf-cla: yes, lgtm, size/S
