Repository kubernetes-incubator/kube-aws, pull requests merged in 2019-04, with the labels that each got.

#1573 BUGFIX: kubeletOptions not applied on controller nodes.
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1571 Capture failures in decrypting assets
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, lgtm, size/XS

#1570 Capture failures in decrypting assets
  core/controlplane/config/templates/cloud-config-controller
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/config/templates/cloud-config-worker
Labels: cncf-cla: yes, size/XS

#1564 Allowing adding arbitrary flags to kubernetes core components through plugins
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  pkg/api/kubernetes.go
  pkg/api/types.go
  pkg/model/compiler.go
  pkg/model/config.go
  pkg/model/node_pool_config.go
  pkg/model/stack_new.go
  plugin/clusterextension/extras.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1575 Allow plugins to add CFN tags and outputs
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/etcd.json.tmpl
  builtin/files/stack-templates/network.json.tmpl
  builtin/files/stack-templates/node-pool.json.tmpl
  core/root/cluster.go
  core/root/template_params.go
  pkg/api/plugin.go
  pkg/model/stack_new.go
  pkg/model/types.go
  plugin/clusterextension/extras.go
  test/integration/plugin_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1582 Remove LaunchTemplateName from the LaunchTemplate
  builtin/files/stack-templates/node-pool.json.tmpl
Labels: cncf-cla: yes, size/XS
