Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-02, with the labels that each got.

#1828 Added an option to Skip IOPS verification in ETCD
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-etcd
  pkg/api/cluster.go
  pkg/api/types.go
Labels: cncf-cla: yes, lgtm, size/M

#1830 incorrect typha resources
  pkg/api/cluster.go
Labels: cncf-cla: yes, size/XS

#1832 v0.15.x branch: Make cloud-controller-manager an experimental feature
  build
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/node_pool_compile.go
  pkg/model/node_pool_config.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XL

#1834 Added back in --configure-cloud-routes=false
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1836 Migrate to flatcar linux from coreos
  cmd/init.go
  coreos/amiregistry/amiregistry.go
  flatcar/amiregistry/amiregistry.go
  flatcar/amiregistry/reliable_http.go
  flatcar/amiregistry/reliable_http_test.go
  pkg/model/compiler.go
  pkg/model/node_pool_compile.go
Labels: cncf-cla: yes, size/L

#1835 cloud-controller-manager/CSI - experimental features
  build
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/etcdadm
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/node_pool_compile.go
  pkg/model/node_pool_config.go
  test/integration/maincluster_test.go
Labels: cncf-cla: yes, size/XL
