Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-07, with the labels that each got.

#1878 Remove danielfm from OWNERS and SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, size/XS

#1877 Add proper indentation to additional zone CoreDNS config
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1880 [v0.12.x] [Unmaintained branch] Disable Flatcar auto-updates
  core/controlplane/config/templates/cloud-config-controller
  core/etcd/config/templates/cloud-config-etcd
  core/nodepool/config/templates/cloud-config-worker
Labels: cncf-cla: yes, size/M

#1879 [v0.15.0] Switch CoreOS to Flatcar
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  builtin/files/userdata/cloud-config-worker
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-4-update.md
  docs/tutorials/quick-start.md
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, lgtm, size/M

#1874 aws-iam-authenticator: upgrade to 0.5.0
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/aws-iam-authenticator/files/authentication-token-webhook-config.yaml
  builtin/files/plugins/aws-iam-authenticator/files/controller-kubeconfig.yaml
  builtin/files/plugins/aws-iam-authenticator/files/worker-kubeconfig.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml
  builtin/files/plugins/aws-iam-authenticator/plugin.yaml
  pkg/api/aws_iam.go
  pkg/api/cluster.go
  pkg/model/config.go
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, lgtm, size/M

#1888 Update owners per k/org
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: cncf-cla: yes, do-not-merge/invalid-owners-file, size/M

#1886 Keep newline, so apiserver starts
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1885 Allow injection of CoreDNS configuration for non-root zones
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1887 Upgrade aws auth, fix CF template bug
  builtin/files/plugins/aws-iam-authenticator/files/authentication-token-webhook-config.yaml
  builtin/files/plugins/aws-iam-authenticator/files/controller-kubeconfig.yaml
  builtin/files/plugins/aws-iam-authenticator/files/worker-kubeconfig.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/aws-auth-cm.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/clusterrole.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/clusterrolebinding.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml
  builtin/files/plugins/aws-iam-authenticator/manifests/serviceaccount.yaml
  builtin/files/plugins/aws-iam-authenticator/plugin.yaml
  builtin/files/stack-templates/control-plane.json.tmpl
  docs/getting-started/step-6-configure-add-ons.md
  pkg/api/cluster.go
Labels: cncf-cla: yes, size/L

#1883 [v0.15.x] Allow injection of CoreDNS configuration for non-root zones
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1884 [v0.16.x] Allow injection of CoreDNS configuration for non-root zones
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1890 Fixes
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  cfnstack/cfnstack.go
  credential/encrypted_assets.go
  docs/cli-reference/README.md
Labels: cncf-cla: yes, size/S
