Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-08, with the labels that each got.

#1891 [v0.14.x] Allow dnsmasq to be backed by a local copy of CoreDNS
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/XL

#1898 [v0.17.x] Increase DNS autosacaler memory and add memory limit
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1900 [v0.14.x] CoreDNS Local Templating issue.
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1901 [v0.14.x] Fix reference to .KubeDns.DNSMasq
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1896 [v0.17.x] Allow dnsmasq to be backed by a local copy of CoreDNS
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/XL

#1893 [v0.16.x] Fix etcd certificates when using private zones
  pkg/model/etcd_cluster.go
  pkg/model/etcd_cluster_test.go
Labels: cncf-cla: yes, size/S

#1892 [v0.16.x] KIAM updates to support assumeRoleArn functionalilty
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/kiam/manifests/agent-daemonset.yaml
  builtin/files/plugins/kiam/manifests/agent-tls-secret.yaml
  builtin/files/plugins/kiam/manifests/rbac.yaml
  builtin/files/plugins/kiam/manifests/server-cluster-role-binding.yaml
  builtin/files/plugins/kiam/manifests/server-cluster-role.yaml
  builtin/files/plugins/kiam/manifests/server-daemonset.yaml
  builtin/files/plugins/kiam/manifests/server-tls-secret.yaml
  builtin/files/plugins/kiam/manifests/service-account.yaml
  builtin/files/plugins/kiam/plugin.yaml
Labels: cncf-cla: yes, size/L

#1903 [v0.17.x] Always create required dnsmasq resources
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1902 [v0.14.x] Always create dnsmasq-node-coredns-local.yaml
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/M
