Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-01, with the labels that each got.

#1809 v0.13.x Remove possible blank lines
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1810 v0.14.x Remove possible blank lines
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1811 v0.15.x Remove possible blank lines
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1813 Add proper indentation to extra CoreDNS config
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/XS

#1814 Add proper indentation to extra CoreDNS config
  core/controlplane/config/templates/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1815 Add proper indentation to extra CoreDNS config
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1817 Add proper indentation to extra CoreDNS config
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1816 Add proper indentation to extra CoreDNS config
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1820 Bump golang version to v1.13.5
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1819 Kubernetes 1.16 Support
  build
  builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml
  builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
  builtin/files/plugins/dashboard/manifests/deployment.yaml
  builtin/files/plugins/kiam/manifests/agent-daemonset.yaml
  builtin/files/plugins/kiam/manifests/server-daemonset.yaml
  builtin/files/plugins/kube2iam/manifests/daemonset.yaml
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  contrib/dex/dex.de.yaml
  contrib/dex/ingress/dex.nginx.ing.yaml
  pkg/api/cluster.go
  pkg/api/plugin.go
Labels: cncf-cla: yes, size/XXL

#1824 Fix for #1823
  builtin/files/cluster.yaml.tmpl
Labels: cncf-cla: yes, size/XS

#1827 template: use of InitialConfig to build cluster.yaml
  builtin/files/cluster.yaml.tmpl
Labels: cncf-cla: yes, size/XS
