Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-05, with the labels that each got.

#1847 Fix DisableContainerLinuxAutomaticUpdates data type
  pkg/api/cluster.go
Labels: cncf-cla: yes, size/XS

#1846 [v0.14.x] Improve Canal Configuration
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1848 make flannel subnetLen configurable for big clusters
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/networking.go
Labels: cncf-cla: yes, lgtm, size/S

#1850 Fix ApiServerAggregatorKeyPath unnamed flag
  cmd/render.go
Labels: cncf-cla: yes, lgtm, size/XS

#1852 Flatcar migration for 0.14.x
  builtin/files/cluster.yaml.tmpl
  cmd/init.go
  coreos/amiregistry/amiregistry.go
  flatcar/amiregistry/amiregistry.go
  flatcar/amiregistry/reliable_http.go
  flatcar/amiregistry/reliable_http_test.go
  pkg/model/compiler.go
  pkg/model/node_pool_compile.go
Labels: cncf-cla: yes, lgtm, size/L

#1853 bugfix: flannel SubnetLen expects an int not an string
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1856 [v0.12.x] Flatcar
  cmd/ami.go
  cmd/init.go
  core/controlplane/cluster/cluster_test.go
  core/controlplane/config/config.go
  core/controlplane/config/config_test.go
  core/nodepool/config/config.go
  core/nodepool/config/templates/cloud-config-worker
  core/root/cluster.go
  core/root/config/config.go
  core/root/config/templates/cluster.yaml
  coreos/amiregistry/amiregistry.go
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-4-update.md
  docs/tutorials/quick-start.md
  etcdadm/README.md
  flatcar/amiregistry/amiregistry.go
  flatcar/amiregistry/reliable_http.go
  flatcar/amiregistry/reliable_http_test.go
  model/release_channel.go
  model/volume_mount_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1854 [v0.16.0] Creating a switch to disable ICMP Ping instead of the default allow 0.0.0/0
  builtin/files/cluster.yaml.tmpl
  builtin/files/stack-templates/control-plane.json.tmpl
  builtin/files/stack-templates/network.json.tmpl
  pkg/api/cluster.go
Labels: cncf-cla: yes, lgtm, size/S

#1857 [v0.16.0] Default Admission Controllers
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
Labels: cncf-cla: yes, size/S

#1858 [v0.16.0] Switch kubernetes.io/cluster/X tag value to "owned".
  builtin/files/plugins/cluster-autoscaler/plugin.yaml
  builtin/files/stack-templates/root.json.tmpl
Labels: cncf-cla: yes, size/XS

#1859 [v0.16.0] Allow custom port name for kiam
  builtin/files/cluster.yaml.tmpl
  builtin/files/plugins/dashboard/manifests/deployment.yaml
  builtin/files/plugins/kiam/manifests/service.yaml
  builtin/files/plugins/kiam/plugin.yaml
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1860 [v0.16.0] Allow use of PodAutoscalerUseRestClient without addon metrics-server.
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/kubernetes.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/M

#1861 [v0.16.0] Bump Kubernetes version
  build
  builtin/files/cluster.yaml.tmpl
Labels: cncf-cla: yes, size/XS

#1864 [v0.16.0] Improve Canal Configuration
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/L

#1863 [v0.16.0] Switch CoreOS to Flatcar
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  cmd/init.go
  coreos/amiregistry/amiregistry.go
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-4-update.md
  docs/tutorials/quick-start.md
  flatcar/amiregistry/amiregistry.go
  flatcar/amiregistry/reliable_http.go
  flatcar/amiregistry/reliable_http_test.go
  pkg/model/compiler.go
  pkg/model/node_pool_compile.go
Labels: cncf-cla: yes, size/L

#1866 [v0.17.0] - Square Master before v0.16.x branch split.
  builtin/files/cluster.yaml.tmpl
  builtin/files/etcdadm/README.md
  cmd/init.go
  coreos/amiregistry/amiregistry.go
  docs/cli-reference/README.md
  docs/getting-started/step-2-render.md
  docs/getting-started/step-4-update.md
  docs/tutorials/quick-start.md
  flatcar/amiregistry/amiregistry.go
  flatcar/amiregistry/reliable_http.go
  flatcar/amiregistry/reliable_http_test.go
  pkg/model/compiler.go
  pkg/model/node_pool_compile.go
Labels: cncf-cla: yes, size/L
