Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-09, with the labels that each got.

#1899 [v0.14.x] Adds 'disable' flag for kubedns
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, lgtm, size/S

#1894 [v0.16.x] Fix node name labelling in v0.16.x clusters.
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-worker
  make/test
Labels: cncf-cla: yes, size/L

#1895 [v0.16.x] Allow dnsmasq to be backed by a local copy of CoreDNS
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, size/XL

#1904 [v0.17.x] Fix reference to .KubeDns.DNSMasq
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1905 [v0.16.x] disables old kubedns when coredns-local enabled.
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1906 [v0.17.x] disables old kubedns when coredns-local enabled
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/S

#1908 [v0.17.x] Disable Flatcar Updates
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, size/M

#1909 [v0.16.x] Disable Flatcare Updates
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, size/M

#1910 [v0.14.x] Disable Flatcar Updates
  builtin/files/userdata/cloud-config-controller
  builtin/files/userdata/cloud-config-etcd
  builtin/files/userdata/cloud-config-worker
Labels: cncf-cla: yes, size/M

#1911 Fix trailing whitespaces in template
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1912 Update README.md
  README.md
Labels: cncf-cla: yes, size/L

#1913 chore: Auto-merge PRs when approved and CLA-signed
  .mergify.yml
Labels: cncf-cla: yes, size/S
