Repository kubernetes-incubator/kube-aws, pull requests merged in 2020-06, with the labels that each got.

#1868 Fix typo, packr -> tparse
  make/test
Labels: cncf-cla: yes, lgtm, size/XS

#1869 Bump golang to v1.14.3
  .travis.yml
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS

#1867 [v0.16.1] Fix rendering for openICMP
  builtin/files/stack-templates/control-plane.json.tmpl
Labels: cncf-cla: yes, size/XS

#1870 [v1.16.1] Update API version for deployment, as v1beta1 is deprecated.
  builtin/files/userdata/cloud-config-controller
Labels: cncf-cla: yes, size/XS

#1873 Migrate to new s3 URL method
  pkg/api/assets.go
  pkg/api/region.go
Labels: cncf-cla: yes, lgtm, size/S

#1875 Allow injection of CoreDNS configuration for non-root zones
  builtin/files/cluster.yaml.tmpl
  builtin/files/userdata/cloud-config-controller
  pkg/api/cluster.go
  pkg/api/types.go
  pkg/model/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/M
